### ISSUE TITLE
Little Snitch recipes do not actually install Little Snitch

### ISSUE THREAD

**Issue by homebysix** [smithjw/smithjw-recipes#1]
As currently written, the Little Snitch recipes simply place the Little Snitch Installer app in the Applications folder, which does not result in a full installation of the software. Additional processing may be required in the pkg recipe.

**Comment by smithjw** [comment]
Removed Little Snitch from the master branch (18ed6be232c0ff03306a7aab2a5619ca4033e563) and will work on it in a separate branch (https://github.com/smithjw/smithjw-recipes/tree/littleSnitch)
